services:
  movie-server:
    build: .
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      MAIN_URL: ${MAIN_URL}
      PORT: 3000
      DOWNLOAD_DIR: /downloads
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ${DOWNLOAD_HOST_PATH:-D:/HA/PlexMedia}:/downloads
